to install tensorflow, do:
"pip install tensorflow==1.13.0rc2"
on your local terminal 

In [1]:
import tensorflow as tf
import numpy as np

C:\Users\hyeon\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x = tf.constant(2)
y = tf.constant(6)
A =  tf.constant(10.0, shape=[2, 3])

Now to obtain the values from tensorflow, you have to run the session

In [5]:
sess =  tf.Session()
sess.run([x*y])

[12]

In [4]:
sess.run(A)

array([[10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [6]:
B = tf.constant(2.0, shape = [3,2])
P = tf.matmul(A,B)

In [7]:
sess.run(P)

array([[60., 60.],
       [60., 60.]], dtype=float32)

In [14]:
thing = tf.placeholder(tf.float32, shape=[2,1])
hiddenlayer =tf.layers.dense(inputs=thing ,units=5, activation = tf.nn.relu)
output =tf.layers.dense(inputs=hiddenlayer ,units=1, activation = None)

In [17]:
X = np.array([[1],[1]])
# print(X.shape)
input_dict = {thing: X}
sess.run(tf.global_variables_initializer())
sess.run(output,feed_dict =input_dict )

array([[-0.72190046],
       [-0.72190046]], dtype=float32)

Now let's make the neural network learn.

To make a neural network learn, we are going to make a decent network first. For our network, we will be using the activation function relu, which is a good general to-go activation function to learn more about activation function, please read the wikipedia article on activation functions

In [26]:
learning_rate=0.005
input_= tf.placeholder(tf.float32, shape=[None,1])
target_value_= tf.placeholder(tf.float32, shape=[None,1])
hiddenlayer = tf.layers.dense(input_,
                                units = 10,
                                activation = tf.nn.relu)
output=tf.layers.dense(hiddenlayer,
                                units = 1,
                                activation = None)
loss = (output-target_value_)**2
trainer = tf.train.AdamOptimizer(learning_rate).minimize(loss)
        
        

So let's test our NN with an arbitrary function: x^3

In [27]:
def f(x):
    return x**3

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1500):
    x= np.random.randint(30, size =(1,1))
    input_dict = {input_ :x, target_value_: f(x) }
    predicted_value = sess.run(output,  feed_dict= input_dict)
    if i % 100 == 0 :
        print("cost: ",abs(predicted_value-f(x)))
    sess.run(trainer , feed_dict=input_dict)
    

cost:  [[5838.60300541]]
cost:  [[122.77350044]]
cost:  [[10620.50902748]]
cost:  [[21867.8002243]]
cost:  [[662.93328857]]
cost:  [[15.85521317]]
cost:  [[28.88982773]]
cost:  [[53.68497849]]
cost:  [[70.81549072]]
cost:  [[35.85035324]]
cost:  [[9738.16760254]]
cost:  [[165.46794128]]
cost:  [[198.04376221]]
cost:  [[64.63446045]]
cost:  [[8877.07800293]]


Aight, now let's test the accuracy of our neural network

In [28]:
for i in range(5):
    x= np.random.randint(30, size =(1,1))
    input_dict = {input_ :x, target_value_: f(x) }
    value = sess.run(output,  feed_dict= input_dict)
    print("Predicted Value: ", value)
    print("Real Value: ", f(x))

Predicted Value:  [[2530.223]]
Real Value:  [[21952]]
Predicted Value:  [[2530.223]]
Real Value:  [[21952]]
Predicted Value:  [[791.09894]]
Real Value:  [[512]]
Predicted Value:  [[356.31787]]
Real Value:  [[27]]
Predicted Value:  [[2095.442]]
Real Value:  [[12167]]


That did not work well, so let's upgrade our neural network with more layers and nodes per layer. Let's go with four hiddenlayers and 500 nodes per layer.

In [30]:
input_= tf.placeholder(tf.float32, shape=[None,1])
target_value_= tf.placeholder(tf.float32, shape=[None,1])
hiddenlayer1 = tf.layers.dense(input_,
                                units = 500,
                                activation = tf.nn.relu)
hiddenlayer2 =tf.layers.dense(hiddenlayer1,
                                units = 500,
                                activation = tf.nn.relu)
hiddenlayer3 =tf.layers.dense(hiddenlayer2,
                                units = 500,
                                activation = tf.nn.relu)
hiddenlayer4 =tf.layers.dense(hiddenlayer3,
                                units = 500,
                                activation = tf.nn.relu)
output=tf.layers.dense(hiddenlayer4,
                                units = 1,
                                activation = None)
loss = (output-target_value_)**2
trainer = tf.train.AdamOptimizer(learning_rate).minimize(loss)
        
        

While training, we also backpropagate a lot of values at once to give more "breath" to the AI while it learns

In [31]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1500):
    x= np.random.randint(30, size =(500,1))
    input_dict = {input_ :x, target_value_: f(x) }
    predicted_value = sess.run(output,  feed_dict= input_dict)
    if i % 100 == 0 :
        print("cost: ",np.max(abs(predicted_value-f(x))))
    sess.run(trainer , feed_dict=input_dict)
    

cost:  24388.833446264267
cost:  7748.060546875
cost:  676.1953125
cost:  324.763671875
cost:  481.802734375
cost:  185.283203125
cost:  722.427734375
cost:  256.671875
cost:  567.375
cost:  277.470703125
cost:  305.478515625
cost:  371.111328125
cost:  153.501953125
cost:  305.080078125
cost:  625.595703125


In [32]:
for i in range(5):
    x= np.random.randint(30, size =(1,1))
    input_dict = {input_ :x, target_value_: f(x) }
    value = sess.run(output,  feed_dict= input_dict)
    print("Predicted Value: ", value)
    print("Real Value: ", f(x))

Predicted Value:  [[15565.045]]
Real Value:  [[15625]]
Predicted Value:  [[511.8297]]
Real Value:  [[512]]
Predicted Value:  [[10592.509]]
Real Value:  [[10648]]
Predicted Value:  [[4085.357]]
Real Value:  [[4096]]
Predicted Value:  [[17489.49]]
Real Value:  [[17576]]


Now that's much closer function approximation. Took a while but we got there.

But wait, there's more! In this notebook we used simple functions, but well implemented neural networks can be trained to imitate more complex and nonlinear functions, such as face recognition, play video games and much more! It's up to you to decide what you want to do!